# Generated by Django 4.0.5 on 2022-06-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_Date',
            field=models.DateField(null=True),
        ),
    ]
